In [1]:
import torch
import torch.nn as nn

In [24]:
def  get_output(x):  
  print("x:", x)
  h_1 = torch.matmul(w_1, x)+ b_1
  print("h_1 before activation:", h_1)
  h_1 =  (h_1>0.0).float()
  print("h_1 after activation:", h_1)
  y = torch.matmul(w_2, h_1) + b_2
  print("y before activation:", y)
  y =  (y>0.0).float()
  print("y after activation:", y)
  print("\n")

In [26]:
w_1 = torch.tensor([[-1, 1, 0, 0], [0, -1, 1, 0], [0, 0, -1, 1]], dtype=torch.float32)
# w_1 = torch.tensor([[-1, 1, 0, 0], [0, -1, 1, 0], [0, 0, -1, 1]], dtype=torch.float32)
b_1 = torch.tensor([0.0,0.0,0.0], dtype=torch.float32)
w_2 = torch.tensor([1, 1, 1], dtype=torch.float32)
b_2 = torch.tensor([-2.0], dtype=torch.float32)
w_1, w_2, b_1, b_2

(tensor([[-1.,  1.,  0.,  0.],
         [ 0., -1.,  1.,  0.],
         [ 0.,  0., -1.,  1.]]),
 tensor([1., 1., 1.]),
 tensor([0., 0., 0.]),
 tensor([-2.]))

In [28]:
# x = torch.rand(4) 
x = torch.tensor([1.0, 2.0, 2.1, -1.])
x_sorted, _ = torch.sort(x)
x_sorted_descending, _ = torch.sort(x, descending=True)
print(x, x_sorted, x_sorted_descending, "\n")

get_output(x)
get_output(x_sorted)
get_output(x_sorted_descending)

tensor([ 1.0000,  2.0000,  2.1000, -1.0000]) tensor([-1.0000,  1.0000,  2.0000,  2.1000]) tensor([ 2.1000,  2.0000,  1.0000, -1.0000]) 

x: tensor([ 1.0000,  2.0000,  2.1000, -1.0000])
h_1 before activation: tensor([ 1.0000,  0.1000, -3.1000])
h_1 after activation: tensor([1., 1., 0.])
y before activation: tensor([0.])
y after activation: tensor([0.])


x: tensor([-1.0000,  1.0000,  2.0000,  2.1000])
h_1 before activation: tensor([2.0000, 1.0000, 0.1000])
h_1 after activation: tensor([1., 1., 1.])
y before activation: tensor([1.])
y after activation: tensor([1.])


x: tensor([ 2.1000,  2.0000,  1.0000, -1.0000])
h_1 before activation: tensor([-0.1000, -1.0000, -2.0000])
h_1 after activation: tensor([0., 0., 0.])
y before activation: tensor([-2.])
y after activation: tensor([0.])


